### ISSUE TITLE
Stuff/gadgets/...

### ISSUE THREAD

**Issue by joren** [brug-be/rubycamp2015#18]
Should we make a list or something on what people can bring?

Stuff like speakers, projector, power plug,...
Not sure if this would fit in the accommodation file or should we create an extra file?

To start with, I can bring a projector.

**Comment by nysthee** [comment]
I think a dedicated list for missing items is a good idea. People can add what is missing and everybody can add their name if they can bring it.

**Comment by toch** [comment]
> Should we make a list or something on what people can bring?
> Stuff like speakers, projector, power plug,...

:+1: good idea

> Not sure if this would fit in the accommodation file or should we create an extra file?

extra file sounds good to me

> To start with, I can bring a projector.

we should have a projector. @Fiyorden is it correct?

**Comment by djouuuuh** [comment]
Are you interested in a pack of block sheets, pens, etc... I can bring this stuff because the company where I work recently changed its name and they're planning to send all these furnitures to the trash (because of the old name/logo on it). This is so sad...

**Comment by toch** [comment]
@djouuuuh some could be interesting, thanks a lot!

**Comment by djouuuuh** [comment]
@toch I'll take care of that, then!

**Comment by ghost** [comment]
If anybody is interested, I can bring my Wii U and mario kart, smash bros, wii sports. Let me know!
Also, I can bring a football and badminton rackets as well.
