### ISSUE TITLE
Food ideas

### ISSUE THREAD

**Issue by ys** [brug-be/rubycamp2015#4]
Hey all, 

With Cloe, we are trying to come up with a great menu for everyday :)

What are the things you would like?

We need some ideas that are compatible with Vegans and Gluten Free folks:)

**Comment by toch** [comment]
Some non meats grilled ideas:
- grilled vegetables such as bell pepper, lettuces, tomatoes, potatoes, eggplant, corn, sweet potatoes
- grilled fruits: banana, peaches, apple, pear, pineapple

check also http://food52.com/blog/10599-8-recipes-for-a-vegetarian-cookout or http://food52.com/recipes/29199-tempeh-kebabs-with-homemade-barbecue-sauce for more elaborated ideas

**Comment by ys** [comment]
For the moment we have, 
pasta bolognese with and without meat.
BBQ with grilled vegetables and meat
Salads with charcuteries.
Everything bring a good part of non meaty stuff

**Comment by ys** [comment]
The idea is to have simple ideas so that we don't pass too much time to cook there.

**Comment by nysthee** [comment]
- :ok_hand: for pasta bolognese, a great replacement for the minced meat is seitan mince or soy mince
- BBQ is a great idea maybe we could add some meat replacers (like sausages or seitan sate's) to have some protein for the non-meat eaters.
- I really like shoarma (can be easily made with and without meat), with garlic sauce and salad
- I also had the idea to make carbonade à la flamande with fries or baked potatoes

**Comment by raphaelescoyez** [comment]
Another option for vegan and gluten-free folks is indian food. 
Check those recipes : 
- Dahl : http://www.ricardocuisine.com/recettes/5684-dhal
- Eggplant curry: http://allrecipes.fr/recette/1486/aubergines-au-curry--baingan-bharta-.aspx

Both are really cheap, easy to cook and will be great with plain rice.
I can bring the spices and cook it.

**Comment by nysthee** [comment]
Sounds really good!!

**Comment by toch** [comment]
:+1: I'm hungry now

**Comment by djouuuuh** [comment]
The indian ideas sound delicious :smile_cat: 

I really don't mind not to eat meat even if I'm not vegan. If it could make things easier for everybody!

**Comment by ys** [comment]
Started a menu

# Friday

## Night (BBQ)
- Sausage + baguette
- Taboule vegan
- green salad
- Chips with salt

# Saturday

## Morning
- Tea, coffee, fruit juice
- Bread, rusks
- jams
- Fruit

## Midday
- charcuterie
- cheese
- tomato salad
- Salad of shredded carrots
- Cucumbers in cream
- bread

## Gouter
- cakes
- Fruits

## night
- Spaghetti bolo
- Spaghetti bolo vegan
- Gluten free pasta

# Sunday

## Morning
- Tea, coffee, fruit juice
- bread, rusks
- jams
- Fruit

## Midday
- fried zucchini curry
- rice

# More
- milk
- beverages

Any comments or help there?

**Comment by djouuuuh** [comment]
No comments except: CAN I COME THE FRIDAY EVENING FOR THE BBQ??? I'm kidding! I'm staying with my cats :smile_cat:

**Comment by toch** [comment]
@ys could we replace sausage/bread by burger/buns? Cc @cveneziani

**Comment by cveneziani** [comment]
Ahah just kidding :wink: 
BBQ is awesome!

**Comment by toch** [comment]
@cveneziani don't you know my famous ruby burgers?

**Comment by cveneziani** [comment]
Nope! Sounds interesting :smile:

**Comment by nysthee** [comment]
I want burgers to instead of tabouleh :) [These](https://www.collectandgo.be/cogo/nl/artikeldetail/14012/BONI-SELECTION-veggie-burgers-1-kg) are vegan and really nice. If needed I can bring some vegan buns but [these](https://www.collectandgo.be/cogo/nl/artikeldetail/32490/BONI-SELECTION-6-hamburgerbroodjes-330-g) are vegan too.

**Comment by ys** [comment]
Cool let's see that yes:)

Thanks a lot for the feedback.

@nysthee you are a vegan that loves junkfood it seems:D

**Comment by nysthee** [comment]
No all the time but when everyone is enjoying burgers its kinda sad eating a salad. :)

**Comment by toch** [comment]
^^ I can prepare my famous ruby sauce then!

**Comment by toch** [comment]
So I need for a Ruby Burger:
- 200g Beef
- Cheddar
- bacon,
- lettuce,
- tomatoes,
- red onions

@nysthee what do you advice as vegan/veggie replacement for beef and bacon. I guess that cheddar has to be removed for veggie, right?

I'll take care of the Ruby sauce in advance :)

**Comment by nysthee** [comment]
@toch to put things a bit clearer:
veggie = people who don't eat meat
vegan = people who don't eat anything that is derived from animal products (no meat, dairy, eggs, honey, ...)
Gluten-free = people allergic to gluten

Foods that are vegan are veggie per definition.

So as for the beef alternative I must recommend the burgers I mentioned above (they are veggie/vegan).  As for a bacon alternative I can recommend [this](http://www.vantastic-foods.com/en/produkt/273/veggie_raeucherspeck_am_stueck/) but it is kinda hard to find in Belgium. A spread based on roasted aubergines should do the trick.

Cheddar should be ok for veggies but obviously not for vegans. Not sure If i'm the only vegan but if so I can bring some plant-based cheese.

**Comment by toch** [comment]
@nysthee thanks a lot for the clarification! Sorry for having switched meaning.

for burgers, let's go for https://www.collectandgo.be/cogo/nl/artikeldetail/14012/BONI-SELECTION-veggie-burgers-1-kg

for buns, let's go for https://www.collectandgo.be/cogo/nl/artikeldetail/32490/BONI-SELECTION-6-hamburgerbroodjes-330-g

for bacon, let's use a eggplant, it could be useful for other dishes

@ys is it ok for your shopping list of friday? Could you do 

> Not sure If i'm the only vegan but if so I can bring some plant-based cheese.

@nysthee According my current list, only one vegan for now.

**Comment by nysthee** [comment]
No problem @toch.

I will bring some plant based cheese (for the burgers, can be eaten on a sandwich the day after). If anything else is needed as a vegan alternative let me know. I live in Gent and some things are easier to find here due to the large veggie/vegan community.

**Comment by toch** [comment]
@ys could you put the menu into the repo? Thanks!

**Comment by toch** [comment]
@ys could you check it https://github.com/brug-be/rubycamp2015/blob/master/menu.md ?

**Comment by ys** [comment]
Sounds good!
Sorry was doing the collect and go to see:D

**Comment by ys** [comment]
Also, we have some budget for snacks and biscuits.

Is it ok if red onions become fried onions?:P

**Comment by nysthee** [comment]
Bicky onions FTW.

**Comment by StanBoyet** [comment]
Let's go all the way @ys .

**Comment by toch** [comment]
@ys may I close the issue?
