### ISSUE TITLE
carpooling file

### ISSUE THREAD

**Issue by norydev** [brug-be/rubycamp2015#8]
How does it work for carpooling? I guess I can't just add my name to a car just like this, it would not be nice for the driver.
So I would appreciate a ride from and to Bruxelles (I do the full weekend), anyone can take me with?
Fabien

**Comment by oana-sipos** [comment]
I have the same issue/dilemma... :)

**Comment by toch** [comment]
I think the best would be to submit a pullrequest where you put yourself into a car, the driver will or won't accept it :).

Cc @joren @Fiyorden @kvzb @leikind

**Comment by joren** [comment]
I think a pull request assigned to the driver sounds good. You can add some comments on where you should be picked or something like that would then help the driver to decide if it possible or not.

**Comment by mlainez** [comment]
Just in case you'd want to use something else, we actually have built a free event carpooling webapp that might be helpful. It's not perfect but it does the job. http://skwizy.com/events/8c92ac18-fc5b-4d30-9ff4-ff0acab006b9

I also added my trip in the file.

**Comment by leikind** [comment]
@mlainez Nice app by the way

I added myself,  going there and coming back on Saturday. Even though I am in Nossegem (Zaventem) picking someone up in the suburbs of Zaventem called Brussels is not a problem

**Comment by toch** [comment]
@oana-sipos did you find a car?
@NoryDev did you find a car?

**Comment by borisrorsvort** [comment]
@leikind I made a request in the app :p We can still arrange pick up zone :)

**Comment by StanBoyet** [comment]
@leikind just like @borisrorsvort , made a request, can arrange pickup zone :) Thanks !

**Comment by leikind** [comment]
@StanBoyet @borisrorsvort guys, did you see in that app that I am going for one day only?
Departs at: 29 August 2015
Returns at: 29 August 2015

**Comment by StanBoyet** [comment]
@leikind Ah, didn't see that ! So you only go on saturday ?

**Comment by leikind** [comment]
Yes
I also mentioned it here on this page in one of my comments.

**Comment by StanBoyet** [comment]
My bad ! 
Well ... it looks like we're still looking for a ride for friday night / sunday afternoon !

**Comment by leikind** [comment]
I wish I could help :-(

**Comment by borisrorsvort** [comment]
Same same :(

**Comment by Bluesmile82** [comment]
Yeah, me too. And Tomasz. We were planning on going by train. Do you think thats possible? (The guitar + amp wont make it though)

**Comment by toch** [comment]
By Train:
- from Central Station, direction Eupen, to Liège-Guillemins, IC 515
- from Liège-Guillemins, direction Marloie, to Tilff, L 5567

Another option is http://www.cambio.be/

**Comment by toch** [comment]
By the way, I'm sure when arrived, some of us can pick you up.

It's possible I'll leave from Brussels by car, if so, I'll have one free seat. I'll tell you when I know.

**Comment by toch** [comment]
Another option is to go by @leikind first in Zaventem, if I'm not wrong?

**Comment by nicefiction** [comment]
I am going by car on early Saturday morning. I could pick you up in Leuven railway station or Brussels Woluwe (metrostop Roodebeek).

**Comment by RasMachineMan** [comment]
Yeah peeps, the bxl team needs a ride :) If we can't get it organized we can always highjack a train :)

**Comment by norydev** [comment]
@toch not yet but I must say I didn't give it too much energy yet.
